---
title: "SISE2601 Schedule"
author: "Nir Grinberg"
date: "4/3/2022"
output: html_document
#rmarkdown::render("index.Rmd", "html_document")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fs)
library(gt)
library(tidyverse)
library(rmarkdown)
# library(xaringan)
```

# Schedule

```{r gen_links, echo=FALSE, eval=FALSE}
xaringans <- dir_info(recurse = 3, glob = "course-materials/*.Rmd") %>% 
  filter(str_detect(path, "slides")) %>%
  filter(!str_detect(path, "setup")) %>%
  select(path) %>%
  # pull(path) %>%
  tibble() %>%
  mutate(
    title = map_chr(path, 
                    function (path) rmarkdown::yaml_front_matter(path)$title),
    html_link = map_chr(path, function (path) paste0("/", path_ext_set(path, "html")) ),
    pdf_link = map_chr(path, function (path) paste0("/", path_ext_set(path, "pdf")) ),
    md_row = paste0("| ", title, " | \\[[html](", html_link, ")\\] |")
  ) %>%
  pull(md_row)
  
  # mutate(title = ) %>%
  # select(path, title)
  # %>% pull(path)
xaringans
```

```{r slides_tbl, echo=FALSE}
slides <- dir_info(recurse = 3, glob = "course-materials/*.Rmd") %>% 
  filter(str_detect(path, "slides")) %>%
  filter(!str_detect(path, "setup")) %>%
  mutate(
    title = map_chr(path, 
          function (path) rmarkdown::yaml_front_matter(path)$title),
    links = map(path, ~ htmltools::tagList(
          htmltools::a(href = paste0("/", path_ext_set(.x, "html")), "html"),
          htmltools::a(href = paste0("/", path_ext_set(.x, "pdf")), "pdf"),
          )),
    links = map(links, ~ gt::html(as.character(.x)))) %>%
    select(path, title, links) 

fmt_table <- function(df) {
  df %>%
    select(-path) %>%
    gt() %>%
    fmt_markdown(columns = c(title)) %>%
    cols_label(week  = md("**Week**"),
               title = md("**Title**"),
               links = md("**Links**")) %>%
    cols_align(align = "left") %>%
    tab_options(table.align='left')
}

filter_units <- function(df, wk, units) {
  df %>% 
    filter(str_detect(path, paste(units, collapse = "|"))) %>%
    add_column(week="", .before = 1) %>%
    mutate(week=ifelse(row_number()==1, wk, ""))
}
```

```{r w1, echo=FALSE}
bind_rows(
  slides %>% filter_units("1", 
      c("u1-d01-welcome", "u1-d02-toolkit-r", "u1-d03-toolkit-git") ),
  slides %>% filter_units("2", 
      c("u2-d01-data-viz", "u2-d02-ggplot2", "u2-d03-viz-num")),
  slides %>% filter_units("3", 
      c("u2-d05-tidy-data", "u2-d06-grammar-wrangle", "u2-d07-single-df",
        "u2-d08-multi-df", "u2-d09-tidying"))
) %>% fmt_table()
```
